export const EventTypes = {
  BusinessCreated: "BusinessCreated",
  AppointmentBooked: "AppointmentBooked",
  AppointmentConfirmed: "AppointmentConfirmed",
  AppointmentCancelled: "AppointmentCancelled",
  AppointmentCompleted: "AppointmentCompleted",
  AppointmentMarkedAsNoShow: "AppointmentMarkedAsNoShow",
  AppointmentMarkedNoShow: "AppointmentMarkedNoShow",
  AppointmentRescheduled: "AppointmentRescheduled",
  AppointmentReminderDue: "AppointmentReminderDue",
  AuditLogCreated: "AuditLogCreated",
  CustomerRiskScoreUpdated: "CustomerRiskScoreUpdated",
  DailyMetricsCalculated: "DailyMetricsCalculated",
  ReminderFailed: "ReminderFailed",
  ReminderScheduled: "ReminderScheduled",
  ReminderSent: "ReminderSent",
  AvailabilityExceptionCreated: "AvailabilityExceptionCreated",
  AvailabilityRuleCreated: "AvailabilityRuleCreated",
  ServiceCreated: "ServiceCreated",
  SlotReassigned: "SlotReassigned",
  SlotReleased: "SlotReleased",
  WaitlistCandidateMatched: "WaitlistCandidateMatched",
  WaitlistEntryCreated: "WaitlistEntryCreated",
  WaitlistOfferAccepted: "WaitlistOfferAccepted",
  WaitlistOfferCreated: "WaitlistOfferCreated",
  WaitlistOfferExpired: "WaitlistOfferExpired",
  WaitlistOfferRejected: "WaitlistOfferRejected",
  MetricsRecalculate: "MetricsRecalculate"
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];

export const EventRoutingKeys = {
  BusinessCreated: "business.created",
  AppointmentBooked: "appointment.booked",
  AppointmentConfirmed: "appointment.confirmed",
  AppointmentCancelled: "appointment.cancelled",
  AppointmentCompleted: "appointment.completed",
  AppointmentMarkedAsNoShow: "appointment.no_show",
  AppointmentMarkedNoShow: "appointment.marked_no_show",
  AppointmentRescheduled: "appointment.rescheduled",
  AppointmentReminderDue: "notification.reminder_due",
  AuditLogCreated: "audit.created",
  CustomerRiskScoreUpdated: "customer.risk_score_updated",
  DailyMetricsCalculated: "metrics.daily_calculated",
  ReminderFailed: "reminder.failed",
  ReminderScheduled: "reminder.scheduled",
  ReminderSent: "reminder.sent",
  AvailabilityExceptionCreated: "availability.exception_created",
  AvailabilityRuleCreated: "availability.rule_created",
  ServiceCreated: "service.created",
  SlotReassigned: "slot.reassigned",
  SlotReleased: "slot.released",
  WaitlistCandidateMatched: "waitlist.candidate_matched",
  WaitlistEntryCreated: "waitlist.entry_created",
  WaitlistOfferAccepted: "waitlist.offer_accepted",
  WaitlistOfferCreated: "waitlist.offer_created",
  WaitlistOfferExpired: "waitlist.offer_expired",
  WaitlistOfferRejected: "waitlist.offer_rejected",
  MetricsRecalculate: "metrics.recalculate"
} as const satisfies Record<keyof typeof EventTypes, string>;

export type EventRoutingKey = (typeof EventRoutingKeys)[keyof typeof EventRoutingKeys];
